server:
  port: 7172

spring: 
   h2:
     console:
       enabled: true
   
   datasource:
       driverClassName: com.mysql.jdbc.Driver 
       url: jdbc:mysql://localhost:3306/rootdb
       username: root
       password: password
   jpa:
     hibernate:
        ddl-auto: update
        show-sql: true
        format_sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
   application:
       name: ORDER-SERVICE


eureka:
  client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
    defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    

